version: "3.1"
services:
  webapi:
    image: "joaopgrassi/appservice-keyvaultref:latest"
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
        SA_PASSWORD: "moviesAdmin_123"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"